### ISSUE TITLE
Please make a release

### ISSUE THREAD

**Issue by irl** [libparistraceroute/libparistraceroute#14]
I'd like to update the Debian package.

Please tag a release that I can base the new Debian package on.

The current version in Debian is 0.92-dev so the version number of your release should be higher than that.

**Comment by ibgp2** [comment]
Dear irl,

The debian package that you mention is the legacy verison of paris-traceroute written in C++. This project is not maintained anymore but is still available here :
https://github.com/libparistraceroute/paris-traceroute-OLD

The whole list of paris-traceroute project is available here :
https://github.com/libparistraceroute

Please let me know for which project you are planning to make a debian package.

Best regards

**Comment by irl** [comment]
I am the owner of a Debian bug to update the paris-traceroute package. My understanding is that the libparistraceroute sources provide a binary that is a successor to the paris-traceroute binary from the old project. I plan to switch the Debian package to use libparistraceroute instead, which will be released in Debian stretch.

**Comment by ibgp2** [comment]
Hi irl,

Ok perfect, thank you for your contribution.

The tag is now created :
https://github.com/libparistraceroute/libparistraceroute/releases/tag/v0.93

Best regards

**Comment by irl** [comment]
Woo. Thanks. (:

Will upload a new package to unstable later today.

**Comment by ibgp2** [comment]
Wonderful :-)

Note that the version of paris-traceroute built above libparistraceroute is not fully backward-compatible. Some type of measurements (e.g. using TCP packets) are not yet supported.
