### ISSUE TITLE
Contradictory LICENSE and COPYING files

### ISSUE THREAD

**Issue by irl** [libparistraceroute/libparistraceroute#15]
In working on the Debian packaging, I have noticed contradictory LICENSE and COPYING files.

Please clarify who holds the copyright for libparistraceroute and the license that it is made available under.

**Comment by ibgp2** [comment]
Hi irl,

The COPYING file was obsolete. This project is under LGPLv3 as stated in the LICENSE file.

Best regards
Marc-Olivier

**Comment by irl** [comment]
The license file contains only a copy of the GNU GPL v3 but does not contain a copyright notice, nor does it contain a license grant.

**Comment by ibgp2** [comment]
Hi irl,

Sorry, indeed it was the wrong license file. I also filled the COPYING file as requested. Please let me know if something is wrong.

Best regards

**Comment by irl** [comment]
Looks good to me. Thanks. (:

**Comment by ibgp2** [comment]
Perfect! Thanks you for your feedback ;)
