### ISSUE TITLE
Are Non root user cant run paris-traceroute ?

### ISSUE THREAD

**Issue by Divesh30** [libparistraceroute/libparistraceroute#26]
terminate called after throwing an instance of 'TrException'
Exception : [ERROR](Server.cc, 51)Cannot create the server : Operation not permittedAborted (core dumped)

**Comment by ibgp2** [comment]
Hello Divesh,

This error is related to the old version of paris-traceroute (the one written in C++) that we do not maintain anymore.

Anyway, Paris-traceroute (new and old versions) requires grants to create raw socket in order to craft probe packets.

Best regards
