### ISSUE TITLE
sniffer.c registers to receive hopopts but does not process them

### ISSUE THREAD

**Issue by drt24** [libparistraceroute/libparistraceroute#3]
In sniffer.c in `create_icmpv6_socket` the line:

```
    ||  (setsockopt(sniffer->icmpv6_sockfd, IPPROTO_IPV6, IPV6_RECVHOPOPTS,  &on, sizeof(on)) == -1) // struct ip6_hbh
```

registers for the receiving of ip6_hbh data as per https://www.ietf.org/rfc/rfc3542.txt
However in `rebuild_ipv6_header` only `IPV6_PKTINFO`, `IPV6_HOPLIMIT` and `IPV6_TCLASS` are handled. `IPV6_HOPOPTS` (which has the value 54 on my system) is not handled.

This results in the following error messages when I run paris-traceroute:

```
Unhandled cmsg of type 54
recv_ipv6_header: error in rebuild_ipv6_header
```

**Comment by ibgp2** [comment]
Hi Daniel,

We should indeed handle this ancillary data. I think that a simple workaround consiss in simply ignoring it for the moment by adding `case IPV6_HOPOPTS: break;`.

Ideally we should properly handle  this data an put it in the right place in `ip6_header` with the appropriate endianness (and the same for each possible value of cmsg->cmsg_type`).

Cheers,
M.O.
